import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`antialiased w-screen min-h-screen flex flex-col items-center justify-center bg-gray-200 mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
